"""Appliers: write a theme into each terminal / editor. Each returns (ok, message)."""
import json, os, re, sys, glob
from pathlib import Path
from core import run, which, backup, hex_to_rgb

HOME = Path.home()
WIN = sys.platform == "win32"
MAC = sys.platform == "darwin"

def _write(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    backup(path)
    path.write_text(text, encoding="utf-8")

def _read_json_lenient(path: Path):
    """Read JSON allowing // and /* */ comments and trailing commas (VS Code style)."""
    if not path.exists():
        return {}
    txt = path.read_text(encoding="utf-8")
    if not txt.strip():
        return {}
    try:
        return json.loads(txt)
    except Exception:
        pass
    # strip comments outside strings
    out, i, n, instr, esc = [], 0, len(txt), False, False
    while i < n:
        c = txt[i]
        if instr:
            out.append(c)
            if esc: esc = False
            elif c == "\\": esc = True
            elif c == '"': instr = False
            i += 1
            continue
        if c == '"':
            instr = True; out.append(c); i += 1; continue
        if c == "/" and i + 1 < n and txt[i+1] == "/":
            while i < n and txt[i] != "\n": i += 1
            continue
        if c == "/" and i + 1 < n and txt[i+1] == "*":
            i += 2
            while i + 1 < n and not (txt[i] == "*" and txt[i+1] == "/"): i += 1
            i += 2
            continue
        out.append(c); i += 1
    cleaned = re.sub(r",(\s*[}\]])", r"\1", "".join(out))
    return json.loads(cleaned)

# ============================== TERMINALS ==============================

def apply_alacritty(t):
    """Alacritty: >=0.13 uses TOML, <=0.12 uses YAML. Detect by version and existing file."""
    if not which("alacritty") and not (HOME/".config"/"alacritty").exists():
        return False, "not installed"
    rc, out, _ = run(["alacritty", "--version"]) if which("alacritty") else (1, "", "")
    ver = (0, 0)
    m = re.search(r"(\d+)\.(\d+)", out)
    if m: ver = (int(m.group(1)), int(m.group(2)))

    base = HOME / ".config" / "alacritty"
    if MAC: base = HOME / ".config" / "alacritty"
    if WIN: base = Path(os.environ.get("APPDATA", HOME)) / "alacritty"

    p = t["palette"]
    use_toml = ver >= (0, 13) or (base/"alacritty.toml").exists()
    if use_toml:
        theme_file = base / "eyecare-theme.toml"
        body = f'''# generated by eyecare-theme -- {t["name"]}
[colors.primary]
background = "{t['bg']}"
foreground = "{t['fg']}"

[colors.cursor]
text = "{t['bg']}"
cursor = "{t['cursor']}"

[colors.selection]
text = "{t['selection_fg']}"
background = "{t['selection_bg']}"

[colors.normal]
black = "{p[0]}"
red = "{p[1]}"
green = "{p[2]}"
yellow = "{p[3]}"
blue = "{p[4]}"
magenta = "{p[5]}"
cyan = "{p[6]}"
white = "{p[7]}"

[colors.bright]
black = "{p[8]}"
red = "{p[9]}"
green = "{p[10]}"
yellow = "{p[11]}"
blue = "{p[12]}"
magenta = "{p[13]}"
cyan = "{p[14]}"
white = "{p[15]}"
'''
        _write(theme_file, body)
        main = base / "alacritty.toml"
        cur = main.read_text(encoding="utf-8") if main.exists() else ""
        imp = 'import = ["' + str(theme_file).replace("\\", "/") + '"]'
        if "eyecare-theme.toml" not in cur:
            if re.search(r"^\s*(general\.)?import\s*=", cur, re.M):
                cur = re.sub(r'^(\s*(?:general\.)?import\s*=\s*\[)',
                             r'\1"' + str(theme_file).replace("\\", "/") + '", ', cur, count=1, flags=re.M)
            else:
                cur = imp + "\n" + cur
            _write(main, cur)
        return True, f"alacritty (toml) -> {theme_file.name}"
    else:
        theme_file = base / "eyecare-theme.yml"
        body = f'''# generated by eyecare-theme -- {t["name"]}
colors:
  primary:
    background: '{t['bg']}'
    foreground: '{t['fg']}'
  cursor:
    text: '{t['bg']}'
    cursor: '{t['cursor']}'
  selection:
    text: '{t['selection_fg']}'
    background: '{t['selection_bg']}'
  normal:
    black:   '{p[0]}'
    red:     '{p[1]}'
    green:   '{p[2]}'
    yellow:  '{p[3]}'
    blue:    '{p[4]}'
    magenta: '{p[5]}'
    cyan:    '{p[6]}'
    white:   '{p[7]}'
  bright:
    black:   '{p[8]}'
    red:     '{p[9]}'
    green:   '{p[10]}'
    yellow:  '{p[11]}'
    blue:    '{p[12]}'
    magenta: '{p[13]}'
    cyan:    '{p[14]}'
    white:   '{p[15]}'
'''
        _write(theme_file, body)
        main = base / "alacritty.yml"
        cur = main.read_text(encoding="utf-8") if main.exists() else ""
        # yaml: replace any existing top-level colors: block with an import
        if "eyecare-theme.yml" not in cur:
            cur = re.sub(r"^colors:\n(?:[ \t]+.*\n|\n)*", "", cur, flags=re.M)
            if re.search(r"^import:", cur, re.M):
                cur = re.sub(r"^(import:\s*\n)", r"\1  - " + str(theme_file) + "\n", cur, count=1, flags=re.M)
            else:
                cur = "import:\n  - " + str(theme_file) + "\n" + cur
            _write(main, cur)
        return True, f"alacritty (yaml) -> {theme_file.name}"

def apply_kitty(t):
    base = HOME/".config"/"kitty"
    if MAC: base = HOME/"Library"/"Preferences"/"kitty"
    if not which("kitty") and not base.exists():
        return False, "not installed"
    p = t["palette"]
    lines = [f"# generated by eyecare-theme -- {t['name']}",
             f"background {t['bg']}", f"foreground {t['fg']}",
             f"cursor {t['cursor']}", f"cursor_text_color {t['bg']}",
             f"selection_background {t['selection_bg']}",
             f"selection_foreground {t['selection_fg']}"]
    for i, c in enumerate(p):
        lines.append(f"color{i} {c}")
    theme_file = base / "eyecare-theme.conf"
    _write(theme_file, "\n".join(lines) + "\n")
    main = base / "kitty.conf"
    cur = main.read_text(encoding="utf-8") if main.exists() else ""
    if "eyecare-theme.conf" not in cur:
        _write(main, cur.rstrip() + "\n\ninclude eyecare-theme.conf\n")
    # live reload all running instances
    run(["kitty", "@", "--to", os.environ.get("KITTY_LISTEN_ON", ""), "set-colors", "-a", str(theme_file)])
    return True, "kitty -> eyecare-theme.conf"

def apply_wezterm(t):
    base = HOME/".config"/"wezterm"
    alt = HOME/".wezterm.lua"
    if not which("wezterm") and not base.exists() and not alt.exists():
        return False, "not installed"
    if WIN: base = Path(os.environ.get("USERPROFILE", HOME))/".config"/"wezterm"
    p = t["palette"]
    body = f'''-- generated by eyecare-theme -- {t["name"]}
return {{
  foreground = "{t['fg']}",
  background = "{t['bg']}",
  cursor_bg  = "{t['cursor']}",
  cursor_fg  = "{t['bg']}",
  cursor_border = "{t['cursor']}",
  selection_fg = "{t['selection_fg']}",
  selection_bg = "{t['selection_bg']}",
  ansi   = {{ {", ".join('"%s"' % c for c in p[:8])} }},
  brights = {{ {", ".join('"%s"' % c for c in p[8:])} }},
}}
'''
    theme_file = base / "eyecare-theme.lua"
    _write(theme_file, body)
    main = base / "wezterm.lua" if base.exists() or not alt.exists() else alt
    cur = main.read_text(encoding="utf-8") if main.exists() else ""
    if not cur.strip():
        _write(main, 'local wezterm = require("wezterm")\n'
                     'local config = wezterm.config_builder()\n'
                     'config.colors = dofile(wezterm.config_dir .. "/eyecare-theme.lua")\n'
                     'return config\n')
        return True, "wezterm -> new wezterm.lua"
    if "eyecare-theme.lua" not in cur:
        return False, "wezterm.lua exists; add manually: config.colors = dofile(wezterm.config_dir..'/eyecare-theme.lua')"
    return True, "wezterm -> eyecare-theme.lua"

def apply_gnome_terminal(t):
    if not which("gsettings"):
        return False, "not installed"
    rc, out, _ = run(["gsettings", "get", "org.gnome.Terminal.ProfilesList", "default"])
    if rc != 0:
        return False, "not installed"
    prof = out.strip().strip("'\"")
    if not prof:
        return False, "no default profile"
    path = f"org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{prof}/"
    pal = "['" + "', '".join(t["palette"]) + "']"
    cmds = [
        ["gsettings", "set", path, "use-theme-colors", "false"],
        ["gsettings", "set", path, "background-color", t["bg"]],
        ["gsettings", "set", path, "foreground-color", t["fg"]],
        ["gsettings", "set", path, "palette", pal],
        ["gsettings", "set", path, "cursor-colors-set", "true"],
        ["gsettings", "set", path, "cursor-background-color", t["cursor"]],
        ["gsettings", "set", path, "cursor-foreground-color", t["bg"]],
        ["gsettings", "set", path, "highlight-colors-set", "true"],
        ["gsettings", "set", path, "highlight-background-color", t["selection_bg"]],
        ["gsettings", "set", path, "highlight-foreground-color", t["selection_fg"]],
        ["gsettings", "set", path, "bold-color-same-as-fg", "true"],
    ]
    errs = [e for c in cmds for r, _, e in [run(c)] if r != 0]
    if errs:
        return False, f"gnome-terminal: {errs[0].strip()[:80]}"
    return True, f"gnome-terminal (profile {prof[:8]})"

def apply_xfce4_terminal(t):
    base = HOME/".config"/"xfce4"/"terminal"
    if not which("xfce4-terminal") and not base.exists():
        return False, "not installed"
    p = t["palette"]
    f = base / "terminalrc"
    cur = f.read_text(encoding="utf-8") if f.exists() else "[Configuration]\n"
    kv = {
        "ColorForeground": t["fg"], "ColorBackground": t["bg"],
        "ColorCursor": t["cursor"], "ColorCursorForeground": t["bg"],
        "ColorSelection": t["selection_fg"], "ColorSelectionBackground": t["selection_bg"],
        "ColorPalette": ";".join(p), "ColorUseTheme": "FALSE",
    }
    if "[Configuration]" not in cur:
        cur = "[Configuration]\n" + cur
    for k, v in kv.items():
        if re.search(rf"^{k}=", cur, re.M):
            cur = re.sub(rf"^{k}=.*$", f"{k}={v}", cur, flags=re.M)
        else:
            cur = re.sub(r"^\[Configuration\]$", f"[Configuration]\n{k}={v}", cur, count=1, flags=re.M)
    _write(f, cur)
    return True, "xfce4-terminal -> terminalrc"

def apply_konsole(t):
    base = HOME/".local"/"share"/"konsole"
    if not which("konsole") and not base.exists():
        return False, "not installed"
    p = t["palette"]
    def rgbs(h):
        return ",".join(str(x) for x in hex_to_rgb(h))
    names = ["Color0","Color1","Color2","Color3","Color4","Color5","Color6","Color7"]
    out = ["[General]", f"Description=EyeCare {t['name']}", "Opacity=1", "Wallpaper=", ""]
    out += ["[Background]", f"Color={rgbs(t['bg'])}", ""]
    out += ["[BackgroundIntense]", f"Color={rgbs(t['bg'])}", ""]
    out += ["[Foreground]", f"Color={rgbs(t['fg'])}", ""]
    out += ["[ForegroundIntense]", f"Color={rgbs(t['fg'])}", ""]
    for i, n in enumerate(names):
        out += [f"[{n}]", f"Color={rgbs(p[i])}", ""]
        out += [f"[{n}Intense]", f"Color={rgbs(p[i+8])}", ""]
    sfile = base / "EyeCare.colorscheme"
    _write(sfile, "\n".join(out))
    # point the default profile at it
    prof = base / "EyeCare.profile"
    _write(prof, f"[Appearance]\nColorScheme=EyeCare\n\n[General]\nName=EyeCare\nParent=FALLBACK/\n")
    krc = HOME/".config"/"konsolerc"
    cur = krc.read_text(encoding="utf-8") if krc.exists() else ""
    if "DefaultProfile=EyeCare.profile" not in cur:
        if re.search(r"^DefaultProfile=", cur, re.M):
            cur = re.sub(r"^DefaultProfile=.*$", "DefaultProfile=EyeCare.profile", cur, flags=re.M)
        elif "[Desktop Entry]" in cur:
            cur = cur.replace("[Desktop Entry]", "[Desktop Entry]\nDefaultProfile=EyeCare.profile", 1)
        else:
            cur = "[Desktop Entry]\nDefaultProfile=EyeCare.profile\n" + cur
        _write(krc, cur)
    return True, "konsole -> EyeCare.colorscheme"

def apply_windows_terminal(t):
    if not WIN:
        return False, "not installed"
    cands = list(glob.glob(str(Path(os.environ.get("LOCALAPPDATA",""))/"Packages"/"Microsoft.WindowsTerminal*"/"LocalState"/"settings.json")))
    cands += list(glob.glob(str(Path(os.environ.get("LOCALAPPDATA",""))/"Packages"/"Microsoft.WindowsTerminalPreview*"/"LocalState"/"settings.json")))
    cands += [str(Path(os.environ.get("LOCALAPPDATA",""))/"Microsoft"/"Windows Terminal"/"settings.json")]
    path = next((Path(c) for c in cands if Path(c).exists()), None)
    if not path:
        return False, "not installed"
    data = _read_json_lenient(path)
    p = t["palette"]
    scheme = {
        "name": "EyeCare", "background": t["bg"], "foreground": t["fg"],
        "cursorColor": t["cursor"],
        "selectionBackground": t["selection_bg"],
        "black": p[0], "red": p[1], "green": p[2], "yellow": p[3],
        "blue": p[4], "purple": p[5], "cyan": p[6], "white": p[7],
        "brightBlack": p[8], "brightRed": p[9], "brightGreen": p[10], "brightYellow": p[11],
        "brightBlue": p[12], "brightPurple": p[13], "brightCyan": p[14], "brightWhite": p[15],
    }
    schemes = [s for s in data.get("schemes", []) if s.get("name") != "EyeCare"]
    schemes.append(scheme)
    data["schemes"] = schemes
    data.setdefault("profiles", {})
    if isinstance(data["profiles"], dict):
        data["profiles"].setdefault("defaults", {})["colorScheme"] = "EyeCare"
    backup(path)
    path.write_text(json.dumps(data, indent=4), encoding="utf-8")
    return True, "windows-terminal -> scheme EyeCare"

def apply_apple_terminal(t):
    if not MAC:
        return False, "not installed"
    return False, "macOS Terminal.app: use iTerm2/Alacritty/kitty, or import manually"

def apply_iterm2(t):
    if not MAC:
        return False, "not installed"
    plist = HOME/"Library"/"Preferences"/"com.googlecode.iterm2.plist"
    if not plist.exists():
        return False, "not installed"
    def comp(h):
        r, g, b = hex_to_rgb(h)
        return {"Red Component": r/255, "Green Component": g/255, "Blue Component": b/255,
                "Color Space": "sRGB", "Alpha Component": 1.0}
    p = t["palette"]
    colors = {"Background Color": comp(t["bg"]), "Foreground Color": comp(t["fg"]),
              "Cursor Color": comp(t["cursor"]), "Cursor Text Color": comp(t["bg"]),
              "Selection Color": comp(t["selection_bg"]), "Selected Text Color": comp(t["selection_fg"]),
              "Bold Color": comp(t["fg"])}
    for i, c in enumerate(p):
        colors[f"Ansi {i} Color"] = comp(c)
    out = HOME/"Library"/"Application Support"/"eyecare-theme"/"iterm2-EyeCare.itermcolors"
    out.parent.mkdir(parents=True, exist_ok=True)
    import plistlib
    out.write_bytes(plistlib.dumps(colors))
    return True, f"iterm2 -> import {out} (Preferences > Profiles > Colors > Import)"

# ============================== EDITORS ==============================

def _vscode_dirs():
    """Return list of (label, user_settings_path, cli_cmd) for VS Code family installs."""
    out = []
    if WIN:
        ad = Path(os.environ.get("APPDATA", HOME))
        cands = [("vscode", ad/"Code"/"User"/"settings.json", "code"),
                 ("vscode-insiders", ad/"Code - Insiders"/"User"/"settings.json", "code-insiders"),
                 ("vscodium", ad/"VSCodium"/"User"/"settings.json", "codium"),
                 ("cursor", ad/"Cursor"/"User"/"settings.json", "cursor")]
    elif MAC:
        ad = HOME/"Library"/"Application Support"
        cands = [("vscode", ad/"Code"/"User"/"settings.json", "code"),
                 ("vscode-insiders", ad/"Code - Insiders"/"User"/"settings.json", "code-insiders"),
                 ("vscodium", ad/"VSCodium"/"User"/"settings.json", "codium"),
                 ("cursor", ad/"Cursor"/"User"/"settings.json", "cursor")]
    else:
        ad = Path(os.environ.get("XDG_CONFIG_HOME", HOME/".config"))
        cands = [("vscode", ad/"Code"/"User"/"settings.json", "code"),
                 ("vscode-insiders", ad/"Code - Insiders"/"User"/"settings.json", "code-insiders"),
                 ("vscodium", ad/"VSCodium"/"User"/"settings.json", "codium"),
                 ("cursor", ad/"Cursor"/"User"/"settings.json", "cursor")]
    for label, path, cli in cands:
        if path.parent.exists() or which(cli):
            out.append((label, path, cli))
    return out

def apply_vscode(t, install_ext=True):
    dirs = _vscode_dirs()
    if not dirs:
        return False, "not installed"
    msgs = []
    for label, path, cli in dirs:
        try:
            data = _read_json_lenient(path)
        except Exception as e:
            msgs.append(f"{label}: unreadable settings.json ({e})")
            continue
        ext = t.get("vscode_ext")
        if install_ext and ext and which(cli):
            rc, out, _ = run([cli, "--list-extensions"])
            if rc == 0 and ext.lower() not in out.lower():
                run([cli, "--install-extension", ext, "--force"])
        data["workbench.colorTheme"] = t["vscode"]
        # terminal colors inside the editor follow the same palette
        p = t["palette"]
        cc = data.get("workbench.colorCustomizations") or {}
        cc.update({
            "terminal.background": t["bg"], "terminal.foreground": t["fg"],
            "terminalCursor.foreground": t["cursor"],
            "terminal.selectionBackground": t["selection_bg"],
            "terminal.ansiBlack": p[0], "terminal.ansiRed": p[1], "terminal.ansiGreen": p[2],
            "terminal.ansiYellow": p[3], "terminal.ansiBlue": p[4], "terminal.ansiMagenta": p[5],
            "terminal.ansiCyan": p[6], "terminal.ansiWhite": p[7],
            "terminal.ansiBrightBlack": p[8], "terminal.ansiBrightRed": p[9],
            "terminal.ansiBrightGreen": p[10], "terminal.ansiBrightYellow": p[11],
            "terminal.ansiBrightBlue": p[12], "terminal.ansiBrightMagenta": p[13],
            "terminal.ansiBrightCyan": p[14], "terminal.ansiBrightWhite": p[15],
        })
        data["workbench.colorCustomizations"] = cc
        data["window.autoDetectColorScheme"] = False
        backup(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        msgs.append(f"{label} -> {t['vscode']}")
    return True, "; ".join(msgs)

_JB_DIRS = ["IntelliJIdea","IdeaIC","PyCharm","PyCharmCE","WebStorm","PhpStorm","CLion",
            "GoLand","RubyMine","Rider","DataGrip","DataSpell","AndroidStudio","RustRover","Aqua"]

def _jetbrains_config_roots():
    if WIN:
        base = Path(os.environ.get("APPDATA", HOME))/"JetBrains"
    elif MAC:
        base = HOME/"Library"/"Application Support"/"JetBrains"
    else:
        base = Path(os.environ.get("XDG_CONFIG_HOME", HOME/".config"))/"JetBrains"
    if not base.exists():
        return []
    roots = []
    for d in sorted(base.iterdir()):
        if d.is_dir() and any(d.name.startswith(p) for p in _JB_DIRS):
            roots.append(d)
    return roots

def apply_jetbrains(t):
    roots = _jetbrains_config_roots()
    if not roots:
        return False, "not installed"
    msgs, any_ok = [], False
    for root in roots:
        opts = root / "options"
        opts.mkdir(parents=True, exist_ok=True)
        # 1) editor color scheme
        cs = opts / "colors.scheme.xml"
        scheme = t["jetbrains"]
        # if the plugin theme isn't installed, fall back to the bundled Darcula/Light
        installed = _jb_scheme_available(root, scheme)
        if not installed:
            scheme = "Darcula" if t["mode"] == "dark" else "Default"
        backup(cs)
        cs.write_text(
            '<application>\n  <component name="EditorColorsManagerImpl">\n'
            f'    <global_color_scheme name="{scheme}" />\n'
            '  </component>\n</application>\n', encoding="utf-8")
        # 2) IDE look and feel (frame chrome)
        laf = opts / "laf.xml"
        theme_id = ("ExperimentalDark", "/themes/expUIDark.theme.json") if t["mode"] == "dark" \
                   else ("ExperimentalLight", "/themes/expUILight.theme.json")
        backup(laf)
        laf.write_text(
            '<application>\n  <component name="LafManager" autodetect="false">\n'
            f'    <laf themeId="{theme_id[0]}" />\n'
            '  </component>\n</application>\n', encoding="utf-8")
        any_ok = True
        note = "" if installed else " (plugin missing, used bundled)"
        msgs.append(f"{root.name} -> {scheme}{note}")
    return any_ok, "; ".join(msgs)

def _jb_scheme_available(root: Path, scheme_name: str) -> bool:
    """Check bundled names and installed plugin jars/xml for the scheme."""
    if scheme_name in ("Darcula", "Default", "Dark", "High contrast", "Light"):
        return True
    # user-installed schemes
    for sub in ("colors", "settingsRepository"):
        d = root / sub
        if d.exists():
            for f in d.rglob("*.icls"):
                if scheme_name.lower().replace(" ", "") in f.stem.lower().replace(" ", ""):
                    return True
    # plugins dir
    if WIN:
        pl = Path(os.environ.get("APPDATA", HOME))/"JetBrains"/root.name/"plugins"
    elif MAC:
        pl = HOME/"Library"/"Application Support"/"JetBrains"/root.name/"plugins"
    else:
        pl = HOME/".local"/"share"/"JetBrains"/root.name
    if pl.exists():
        blob = " ".join(p.name.lower() for p in pl.rglob("*") if p.is_file())
        key = scheme_name.split()[0].lower()
        if key in blob:
            return True
    return False

def apply_neovim(t):
    base = HOME/".config"/"nvim"
    if WIN:
        base = Path(os.environ.get("LOCALAPPDATA", HOME))/"nvim"
    if not which("nvim") and not base.exists():
        return False, "not installed"
    nv = {"gruvbox-dark":"gruvbox","gruvbox-light":"gruvbox","solarized-dark":"solarized",
          "solarized-light":"solarized","nord":"nord","everforest-dark":"everforest",
          "everforest-light":"everforest","one-dark":"onedark","tokyonight-storm":"tokyonight",
          "github-light":"github_light"}
    cs = nv.get(t["id"].replace("-warm",""), "habamax")
    bgv = "dark" if t["mode"] == "dark" else "light"
    f = base / "eyecare-theme.vim"
    _write(f, f'" generated by eyecare-theme -- {t["name"]}\n'
              f'set background={bgv}\n'
              f'silent! colorscheme {cs}\n')
    init = base / "init.lua"
    initv = base / "init.vim"
    if init.exists():
        cur = init.read_text(encoding="utf-8")
        if "eyecare-theme.vim" not in cur:
            _write(init, cur.rstrip() + '\n\npcall(vim.cmd, "source " .. vim.fn.stdpath("config") .. "/eyecare-theme.vim")\n')
    elif initv.exists():
        cur = initv.read_text(encoding="utf-8")
        if "eyecare-theme.vim" not in cur:
            _write(initv, cur.rstrip() + '\nsilent! source ' + str(f) + '\n')
    else:
        _write(init, 'pcall(vim.cmd, "source " .. vim.fn.stdpath("config") .. "/eyecare-theme.vim")\n')
    return True, f"neovim -> {cs} ({bgv})"

def apply_gnome_shell(t):
    """Match the desktop light/dark preference so window chrome doesn't flash white."""
    if not which("gsettings"):
        return False, "not installed"
    rc, out, _ = run(["gsettings", "get", "org.gnome.desktop.interface", "color-scheme"])
    if rc != 0:
        return False, "not installed"
    want = "prefer-dark" if t["mode"] == "dark" else "prefer-light"
    run(["gsettings", "set", "org.gnome.desktop.interface", "color-scheme", want])
    return True, f"gnome desktop -> {want}"

# ============================== REGISTRY ==============================

TARGETS = {
    "alacritty":        apply_alacritty,
    "kitty":            apply_kitty,
    "wezterm":          apply_wezterm,
    "gnome-terminal":   apply_gnome_terminal,
    "xfce4-terminal":   apply_xfce4_terminal,
    "konsole":          apply_konsole,
    "windows-terminal": apply_windows_terminal,
    "iterm2":           apply_iterm2,
    "vscode":           apply_vscode,
    "jetbrains":        apply_jetbrains,
    "neovim":           apply_neovim,
    "gnome-desktop":    apply_gnome_shell,
}

def detect_available():
    """Return list of target names that look installed (cheap probe)."""
    found = []
    probes = {
        "alacritty": lambda: which("alacritty") or (HOME/".config"/"alacritty").exists(),
        "kitty": lambda: which("kitty") or (HOME/".config"/"kitty").exists(),
        "wezterm": lambda: which("wezterm") or (HOME/".config"/"wezterm").exists() or (HOME/".wezterm.lua").exists(),
        "gnome-terminal": lambda: bool(which("gnome-terminal")) and bool(which("gsettings")),
        "xfce4-terminal": lambda: which("xfce4-terminal") or (HOME/".config"/"xfce4"/"terminal").exists(),
        "konsole": lambda: which("konsole") or (HOME/".local"/"share"/"konsole").exists(),
        "windows-terminal": lambda: WIN,
        "iterm2": lambda: MAC and (HOME/"Library"/"Preferences"/"com.googlecode.iterm2.plist").exists(),
        "vscode": lambda: bool(_vscode_dirs()),
        "jetbrains": lambda: bool(_jetbrains_config_roots()),
        "neovim": lambda: which("nvim") or (HOME/".config"/"nvim").exists(),
        "gnome-desktop": lambda: bool(which("gsettings")) and "gnome" in (os.environ.get("XDG_CURRENT_DESKTOP","").lower()),
    }
    for name, fn in probes.items():
        try:
            if fn():
                found.append(name)
        except Exception:
            pass
    return found
